# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  unittest-and-linter:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Unittests
          command: python manage.py test
      - run:
          name: Linter
          command: flake8 --max-line-length=99
  
  build-and-push-docker-image:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            echo $CIRCLE_SHA1 | docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
            docker build -t ${DOCKERHUB_USER}/oc_lettings:$CIRCLE_SHA1 .
            docker push ${DOCKERHUB_USER}/oc_lettings:$CIRCLE_SHA1

  deploy-on-heroku:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: Deploy app on heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SECRET_KEY=${SECRET_KEY} --app ${HEROKU_APP_NAME}
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set DEBUG=${DEBUG} --app ${HEROKU_APP_NAME}
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push web --app ${HEROKU_APP_NAME}
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web --app ${HEROKU_APP_NAME}

workflows:
  sample:
    jobs:
      - unittest-and-linter
      - build-and-push-docker-image:
          requires:
            - unittest-and-linter
          filters:
            branches:
              only:
                - main
      - deploy-on-heroku:
          requires:
            - build-and-push-docker-image
          filters:
            branches:
              only:
                - main

